name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Instalar lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Sincronizar vía SFTP Puro
        env:
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_SERVER }}
        run: |
          lftp -c "
          set sftp:auto-confirm yes
          open sftp://$FTP_HOST
          user $FTP_USER \"$FTP_PASS\"
          mirror -R -v --exclude .git/ --exclude .github/ ./ /homepages/28/d1007113302/htdocs/www/
          bye
          "
